version: '3.2'

services:
   db:
      image: mysql:8.0
      container_name: appsDB
      restart: always
      ports:
       - '3306:3306'
      volumes:
       - db-data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: lnwza007
        MYSQL_USER: supakorn
        MYSQL_PASSWORD: lnwza007

   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin:5.1.0
      container_name: phpmyadmin
      restart: always
      ports:
       - '9999:80'
      environment:
        PMA_HOST: db

volumes:
   db-data:
