version: '3.2'

services:
   app:
      image: phpmyadmin/phpmyadmin:5.1.0
      container_name: local
      restart: always
      ports:
       - '8888:80'
      environment:
        PMA_HOST: "host.docker.internal:4000"
